### ISSUE TITLE
Installer breaks during migration

### ISSUE THREAD

**Issue by hrdchz** [solidusio/solidus_paypal_braintree#244]
It appears that #236 breaks the installer? I get an error about `preferences` when running the migrations, which was introduced in those commits.

Error message:

```
=== 20191122221009 AddBraintreeConfigurationToStores: migrating ================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined local variable or method `preferences' for #<SolidusPaypalBraintree::Configuration:0x00007f99466f4b18>
Did you mean?  preference_type
/home/asdf/vagrants/s.jumble/db/migrate/20191122221009_add_braintree_configuration_to_stores.solidus_paypal_braintree.rb:4:in `up'
/home/asdf/.rbenv/versions/2.6.2/bin/bundle:23:in `load'
/home/asdf/.rbenv/versions/2.6.2/bin/bundle:23:in `<main>'

Caused by:
NameError: undefined local variable or method `preferences' for #<SolidusPaypalBraintree::Configuration:0x00007f99466f4b18>
Did you mean?  preference_type
/home/asdf/vagrants/s.jumble/db/migrate/20191122221009_add_braintree_configuration_to_stores.solidus_paypal_braintree.rb:4:in `up'
/home/asdf/.rbenv/versions/2.6.2/bin/bundle:23:in `load'
/home/asdf/.rbenv/versions/2.6.2/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

```

rails 5.2.3 / ruby 2.6.2 / solidus 2.9.3

I was able to install with `gem 'solidus_paypal_braintree', github: 'solidusio/solidus_paypal_braintree', ref: '3e7bb8074'`

**Comment by luaysuarna** [comment]
Any lucky here? I found same problem

**Comment by luaysuarna** [comment]
I skipped this migration
```
# This migration comes from solidus_paypal_braintree (originally 20161125172005)
class AddBraintreeConfigurationToStores < SolidusSupport::Migration[4.2]
  def up
    Spree::Store.all.each(&:create_braintree_configuration)
  end

  def down
    SolidusPaypalBraintree::Configuration.joins(:store).destroy_all
  end
end

```

and finish all migration, then running back tthe command from rails console. All done! :)

**Comment by waymondo** [comment]
Also noticing this is still broken on master

**Comment by bazfer** [comment]
Any plans to roll back the breaking change? Rather have the installation working properly than an extra feature.

**Comment by hrdchz** [comment]
Installed without issue. Thanks!
